version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: microservivios
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - "33060:3306"
    
  estudiante:
    build: .
    container_name: estudiante-service
    depends_on:
      - mysql-db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=microservivios

volumes:
  mysql-db-data: